### ISSUE TITLE
Fatal error: require(): Failed opening required 'C:\Apache24\htdocs/vendor/autoload.php' 

### ISSUE THREAD

**Issue by issararab** [neo4j-examples/movies-php-neoclient#1]
I am trying to run the application on my localhost however I got all the time the same error popping up:

Warning: require(C:\Apache24\htdocs/vendor/autoload.php): failed to open stream: No such file or directory in C:\Apache24\htdocs\index.php on line 8

Fatal error: require(): Failed opening required 'C:\Apache24\htdocs/vendor/autoload.php' (include_path='.;C:\php\pear') in C:\Apache24\htdocs\index.php on line 8

Can anyone help me solve this problem I really need a solution as soon as possible to start investigating the use of Neo4j in php and start coding my Masters Project ?

**Comment by ikwattro** [comment]
Hi @issararab 

It seems like the dependencies are not installed, did you run `php composer.phar install` ?

**Comment by ronnieyego** [comment]
_Am also getting the same problem working with the amazon web services._

Message:require(C:\xampp\htdocs\LovingColours\application\libraries\amazonSdk/GuzzleHttp/Handler/CurlFactoryInterface.php): failed to open stream: No such file or directory

Filename: amazonSdk/aws-autoloader.php

Fatal error: require(): Failed opening required 'C:\xampp\htdocs\LovingColours\application\libraries\amazonSdk/GuzzleHttp/Handler/CurlFactoryInterface.php' (include_path='.;C:\xampp\php\PEAR ') in C:\xampp\htdocs\LovingColours\application\libraries\amazonSdk\aws-autoloader.php on line 478


someone help
